services:
  - type: web
    name: sentinelai
    env: python
    buildCommand: ""
    startCommand: gunicorn main:app
    envVars:
      - key: CLOUDANT_USERNAME
        sync: false
      - key: CLOUDANT_API_KEY
        sync: false
      - key: CLOUDANT_DB_NAME
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_ID
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_SECRET
        sync: false
      - key: GITHUB_OAUTH_CLIENT_ID
        sync: false
      - key: GITHUB_OAUTH_CLIENT_SECRET
        sync: false
